---
- name: Update APT Cache
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
    autoclean: yes
    autoremove: yes
    update_cache: yes
  vars:
    packages:
    - docker.io
    - python3
    - python3-pip
    - git
    - git-crypt
    - gnupg2
    - bat
    - sshpass

- name: Start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add vagrant user to docker group
  user:
    name: 'vagrant'
    groups: 'docker'
    append: 'yes'

- name: Bat - Setup base directory
  file:
    path: '{{ item.path }}'
    group: 'vagrant'
    owner: 'vagrant'
    state: directory
  with_items:
  - { path: '{{ bat_path }}' }

- name: Bat - Create symbolic link 
  file:
    src: "/usr/bin/batcat"
    dest: "{{ item.path }}/bat"
    state: link
  with_items:
  - { path: '{{ bat_path }}' }
