---
- name: SSH - Setup basic directories
  file:
    path: '{{ item.path }}'
    group: 'vagrant'
    owner: 'vagrant'
    state: directory
  with_items:
  - { path: '{{ ssh_path }}' }

- name: SSH - Copy .ssh files
  copy:
    src:  'ssh_keys/{{ item.ssh_key }}'
    dest: '{{ ssh_path }}/{{ item.ssh_key }}'
    group: 'vagrant'
    owner: 'vagrant'
    mode: '{{ item.mode }}'
  with_items: '{{ ssh_files }}'

- name: Authorize key
  authorized_key:
    user: 'vagrant'
    state: present
    key: "{{ lookup('file', '{{ ssh_path }}/id_rsa.pub') }}"